server: 
  port: 53030
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:53000/eureka/

spring:
##################### DB #####################
  datasource: 
    url: jdbc:mysql://localhost:3306/convert_file?useUnicode=true&characterEncoding=utf-8&characterSetResults=utf8&serverTimezone=Asia/Shanghai&useSSL=false&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: root

    ##################### redis #####################
#  redis:
#    #cluster:
#    #max-redirects: ''   # （普通集群，不使用则不用开启）在群集中执行命令时要遵循的最大重定向数目。
#    #nodes: ''  # （普通集群，不使用则不用开启）以逗号分隔的“主机：端口”对列表进行引导。
#    database: 0   # 连接工厂使用的数据库索引
#    host: 127.0.0.1
#    password: foobared123
#    port: 6379
#    pool:
#      maxActive: 5000  # 池在给定时间可以分配的最大连接数。使用负值无限制。
#      maxIdle: 5000    # 池中“空闲”连接的最大数量。使用负值表示无限数量的空闲连接。
#      maxWait: 10000   # 连接分配在池被耗尽时抛出异常之前应该阻塞的最长时间量（以毫秒为单位）。使用负值可以无限期地阻止。
#      minIdle: 10    # 目标为保持在池中的最小空闲连接数。这个设置只有在正面的情况下才有效果。
#      #sentinel:
#      #master: ''    # （哨兵模式，不使用则不用开启）Redis服务器的名称。
#      #nodes: ''     # （哨兵模式，不使用则不用开启）主机：端口对的逗号分隔列表。
#    ssl: false       # 启用SSL支持
#    timeout: 60000       # 以毫秒为单位的连接超时。

apache:
  rocketmq:
    namesrvAddr: localhost:9876
            
logging: 
  config: classpath:log4j2-dev.xml
  
swagger: 
  enable: true

# ffmpeg存放路径，mp4,mp3转码后提供给wowza使用的存放路径。
file:
  ffmpeg:
    path: E:/software/ffmpeg/bin/ffmpeg.exe
  videoMp4:
    path: E:/videoMp4/
  audioMp3:
    path: E:/audioMp3/

convert:
  ffmpeg: xxxxx      #ffmpeg路径
  videoTemp: xxxxx   # 转码后临时存放视频路径
  aideoTemp: xxxxx   # 转码后临时存放音频路径
  SeparateSize: 50M
  content: xxxxx      #WOWZA VOD指定路径



